import Head from 'next/head';
import Hero from '../components/Hero';
import Categories from '../components/Categories';
import { client } from '../graphql/client';
import { GET_CATEGORIES } from '../graphql/GET_CATEGORIES';
import { useYContext } from '../contexts/YContext';
import { useLocomotiveScroll } from 'react-locomotive-scroll';
import { useEffect } from 'react';

export default function Home(props) {
  const { scroll } = useLocomotiveScroll();
  const { setY } = useYContext()

  useEffect(() => {
    if (scroll) {
      const element = scroll?.el;

      scroll.on('scroll', function (t) {
        document.documentElement.setAttribute('data-direction', t.direction);
        setY(t.scroll.y);
      });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scroll]);

  return (
    <>
      <Head>
        <title>Gaming World</title>
        <meta name='Gaming World' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Gaming world' description='For you' />
      <Categories categories={props} />
    </>
  );
}

export async function getServerSideProps() {
  const data = await client.query({
    query: GET_CATEGORIES,
  });

  return {
    props: {
      data,
    },
  };
}
