import Head from 'next/head';
import Hero from '../components/Hero';
import AboutNew from '../components/AboutNew';
import { client } from '../graphql/client';
import { GET_CATEGORIES } from '../graphql/GET_CATEGORIES';
import SlidingText3D from '../components/SlidingText3D';
import { useLocomotiveScroll } from 'react-locomotive-scroll';
import { useEffect, useState } from 'react';
import Footer from '../components/Footer';

export default function Home(props) {
  const { scroll } = useLocomotiveScroll();
  const [Y, setY] = useState(0);

  useEffect(() => {
    if (scroll) {
      const element = scroll?.el;

      scroll.on('scroll', function (t) {
        document.documentElement.setAttribute('data-direction', t.direction);
        // console.log('t-lscroll', t.scroll.y);
        setY(t.scroll.y);
      });
    }
  }, [scroll]);

  return (
    <>
      <Head>
        <title>Gaming World</title>
        <meta name='Gaming World' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Gaming world' description='For you' />

      <AboutNew categories={props} />
      <SlidingText3D Y={Y} />
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  const data = await client.query({
    query: GET_CATEGORIES,
  });

  return {
    props: {
      data,
    },
  };
}
